title:              "Styleguide"
email:              "someone@bvn.com.au"
description:        "This is how to use our graphic assets"
baseurl:           "/styleguide/"
url:                "http://bvn-architecture.github.io" # the base hostname & protocol for your site
twitter_username:   "architecturebvn"
github_username:    "bvn-architecture"
facebook-publisher: "https://www.facebook.com/pages/BVN-Architecture/131354776914013?fref=ts"
publisher:          "BVN"
publisher_website:  "http://bvn.com.au/"

# Build settings
markdown:     "kramdown"

encoding:     "utf-8"
permalink:    "none"
highlighter:  "rouge"

sass:
    sass_dir: _sass
